### ISSUE TITLE
приставката не не работи  от началото на април

### ISSUE THREAD

**Issue by stoilovnikolai** [ByJohnie/plugin.video.mtelnow#8]

**Comment by lukavia** [comment]
Ще ни трябва по подробно описание от "не работи" 
Аз си я ползвам всеки ден. 
Какво точно правите и при кое действие престава да работи? 
също така моля да прикачите целия лог като файл.

**Comment by stoilovnikolai** [comment]
При кликване върху канал премигва и до там.Няма проблем с логването и зареждането на каналите.
[kodi.log](https://github.com/ByJohnie/plugin.video.mtelnow/files/4546167/kodi.log)

**Comment by lukavia** [comment]
Като кликнете на канал в менюто "Телевизия" или в Менюто "Програма" 
Т.е. искате да гледате в реално време или да гледате някое старо предаване?

**Comment by stoilovnikolai** [comment]
Става дума за менюто телевизия. Т.е. в реално време.Имам съмнени за проблем с nputstream.adaptive . В един от логовете засякох изявление че не може да свали някакъв каталог! може и да греша

**Comment by stoilovnikolai** [comment]
Аз ползвам Libreelec 9.1.2 - Kodi 18.6. -RPi4

**Comment by lukavia** [comment]
Да. Знам какъв е проблема. В началото на април някой от сървърите на А1 си преиздадоха ssl сертификатите и ползват издател, който не е включен в сертификатите по подразбиране на kodi (kodi си ползва собствен bundle с издатели). 
Прикачам тук липсващия сертификат. 
Виждам, че ползвате LibreElec (като мен). 
Пробвайте да направите следното. 
1. Разархивирайте файл-а и го качете в /storage на устройство. 
2. С ssh изпълнете: `cat /usr/lib/ssl/cert.pem /storage/digicert.pem > /storage/cacert.pem`
3. след това добавете `SSL_CERT_FILE=/storage/cacert.pem` във файла /storage/.config/kodi.conf (ако несъществува, го създайте) 
4. Рестартирайте устройството. 

Това би трябвало да е достатъчно
[digicert.zip](https://github.com/ByJohnie/plugin.video.mtelnow/files/4546276/digicert.zip)

**Comment by stoilovnikolai** [comment]
Направих всичко точно така,но не тръгна.

**Comment by lukavia** [comment]
Хмм колко голям се получи /storage/cacert.pem?

**Comment by lukavia** [comment]
Пробвайте и да изпълните това `cp /storage/digicert.pem /storage/.config/cacert.pem` и рестартирайте отново моля.

**Comment by stoilovnikolai** [comment]
Отново не става.

**Comment by stoilovnikolai** [comment]
Ще нулирам настройките и ще пробвам на чисто

**Comment by stoilovnikolai** [comment]
Само с този ред без нищо друго cp /storage/digicert.pem /storage/.config/cacert.pem тръгна
